mark hdaps_whitelist as initconst instead of initdata
this fixes build issues with grsec enabled kernels:

DKMS make.log for tp_smapi-dkms-0.42 for kernel 4.6.4.201607112205-1-grsec (x86_64)
Sat Jul 16 01:31:14 EDT 2016
make -C /usr/lib/modules/4.6.4.201607112205-1-grsec/build M=/var/lib/dkms/tp_smapi-dkms/0.42/build O=/usr/lib/modules/4.6.4.201607112205-1-grsec/build modules
make[1]: Entering directory '/usr/lib/modules/4.6.4.201607112205-1-grsec/build'
make[2]: Entering directory '/usr/lib/modules/4.6.4.201607112205-1-grsec/build'
  CC [M]  /var/lib/dkms/tp_smapi-dkms/0.42/build/thinkpad_ec.o
/var/lib/dkms/tp_smapi-dkms/0.42/build/thinkpad_ec.o: warning: objtool: thinkpad_ec_exit(): can't find starting instruction
  CC [M]  /var/lib/dkms/tp_smapi-dkms/0.42/build/tp_smapi.o
/var/lib/dkms/tp_smapi-dkms/0.42/build/tp_smapi.o: warning: objtool: tp_exit(): can't find starting instruction
  CC [M]  /var/lib/dkms/tp_smapi-dkms/0.42/build/hdaps.o
/var/lib/dkms/tp_smapi-dkms/0.42/build/hdaps.c:738:33: error: constified variable ‘hdaps_whitelist’ placed into writable section ".init.data"
 struct dmi_system_id __initdata hdaps_whitelist[] = {
                                 ^~~~~~~~~~~~~~~
make[3]: *** [/usr/lib/modules/4.6.4.201607112205-1-grsec/build/scripts/Makefile.build:298: /var/lib/dkms/tp_smapi-dkms/0.42/build/hdaps.o] Error 1
make[2]: *** [/usr/lib/modules/4.6.4.201607112205-1-grsec/build/Makefile:1437: _module_/var/lib/dkms/tp_smapi-dkms/0.42/build] Error 2
make[2]: Leaving directory '/usr/lib/modules/4.6.4.201607112205-1-grsec/build'
make[1]: *** [Makefile:146: sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.6.4.201607112205-1-grsec/build'
make: *** [Makefile:46: modules] Error 2

thanks: Sean Behan <seanwbehan@riseup.net>